### ISSUE TITLE
Uniface

### ISSUE THREAD

**Issue by TranThanh96** [HaiyuWu/SOTA-Face-Recognition-Train-and-Test#1]
does your code (patial fc + uniface) work on wf42m? have you tried to train uniface + patial fc?

**Comment by HaiyuWu** [comment]
I don't think dataset matters as long as you process it to the correct format, so my answer is yes.

**Comment by TranThanh96** [comment]
@HaiyuWu  thank you for your great work! Do you have a plan to benchmark on webface42m dataset ?

**Comment by HaiyuWu** [comment]
No problem. I am not planning to do it, because webface42m is too much for me to train. T . T
