### ISSUE TITLE
Modifying face alignment method

### ISSUE THREAD

**Issue by HectorPenades** [HaiyuWu/SOTA-Face-Recognition-Train-and-Test#3]
Hi,

I am working with AdaFace and was wondering what method is used for facial alignment before generating the face embeddings. I would like to know:

What face alignment method is used in this code by default (if any)?
Where in the codebase can I modify or replace the alignment method with my own implementation?
Any guidance on this would be greatly appreciated.

Thank you!

**Comment by HaiyuWu** [comment]
I directly use the images from [insightface](https://github.com/deepinsight/insightface/tree/master/recognition/_datasets_), so they are already cropped and aligned. I think this repo also integrates the face alignment method, so you can try to figure it out there.

Another repo I am using in other project is [img2pose](https://github.com/vitoralbiero/img2pose).
