### ISSUE TITLE
warmup doesn't work

### ISSUE THREAD

**Issue by ericyq** [HaiyuWu/SOTA-Face-Recognition-Train-and-Test#6]
config.warmup_epoch = 1

when training, warmup that didn't work

**Comment by HaiyuWu** [comment]
> config.warmup_epoch = 1
> 
> when training, warmup that didn't work

Hi, thanks for your reply. I have double-checked the code and I think it works well.
I want you to make sure that both ```config.scheduler=True``` and ```config.warmup_epoch=1``` are set.

To check if it works, you can print the value of default ```lr``` and the actual ```lr``` by adding these two lines.
![image](https://github.com/user-attachments/assets/b79b4b52-b842-48d6-ba6f-53d071395b67)
I got this result by using the vit_s.py configuration file.
![image](https://github.com/user-attachments/assets/e8c1b658-8ffc-4ebd-a287-da516cb92412)

Let me know if it still does work for you.

**Comment by ericyq** [comment]
oh, 
>>>config.warmup_epoch = 1
config.scheduler = False

need to set config.scheduler =True. ok, I try on
